export const TRUSTED_JS_OPTION_PATHS = [
  "preset",
  "leader",
  "startMode",
  "cursor.insert",
  "cursor.normal",
  "cursor.visual",
  "cursor.visualLine",
  "cursor.visualBlock",
  "keymap.actionPresets",
  "keymap.operatorMotions",
  "ui.status.enabled",
  "ui.status.position",
  "ui.status.items",
  "ui.mode.enabled",
  "ui.mode.labels",
  "ui.mode.narrowLabels",
  "ui.selection.enabled",
  "ui.selection.previewMaxChars",
  "ui.cursorPosition.enabled",
  "ui.cursorPosition.base",
  "ui.cursorPosition.format",
  "ui.workbench.reservedRows",
  "macros.enabled",
  "macros.slots",
  "macros.maxReplaySteps",
  "marks.enabled",
  "marks.slots",
  "search.highlight",
  "search.highlightCurrent",
  "search.clearOnCancel",
  "search.clearOnInsert",
  "search.maxHighlights",
  "exCommand.autocomplete",
  "feedback.noop",
  "promptStructures.enabled",
  "promptStructures.targets",
  "promptTransforms.enabled",
  "promptTransforms.actions",
  "promptTransforms.commands",
  "whichKey.enabled",
  "whichKey.groups",
] as const;

export type TrustedJsOptionPath = (typeof TRUSTED_JS_OPTION_PATHS)[number];
